### ISSUE TITLE
for brain tumor segmention

### ISSUE THREAD

**Issue by cc1609130201** [vikolss/DACS#17]
if i wanna use this model in BraTS data . the first thing i need to do , is to get a good model in BraTs data based on deeplabv2, is that?

**Comment by vikolss** [comment]
The code should be able to be used directly on any segmentation dataset, so long as the format of the data is the same as the data used in this repository. However, perhaps a pretraining other than Imagenet, which we have used, is more appropriate for your task. In that case it could be beneficial for you to use that pretraining instead (this might require some tweaking). You could also use another model entirely, i.e. not Deeplabv2. This may require some more work on your part, although it could prove to be more successful since several more sophisticated models have been introduced since Deeplabv2.

Hope this helps :)
