### ISSUE TITLE
The parameters of the  experiment of the cowMix mask

### ISSUE THREAD

**Issue by manmanjun** [vikolss/DACS#8]

**Comment by manmanjun** [comment]
In the /utils/transformmasks.py,  how are the parameters of sigma, p set in the functions generate_cow_mask?

**Comment by vikolss** [comment]
Hi, sorry for late response. The parameters used are the same as the ones used in the paper [ClassMix: Segmentation-Based Data Augmentation for Semi-Supervised Learning](https://arxiv.org/abs/2007.07936), namely p = 0.5 and sigma taken randomly in the range [8,32]. See this [repo](https://github.com/WilhelmT/ClassMix/blob/master/trainSSL.py) for details on the generation and implementation.
The reason for using these particular values is partly because they were used in [this](https://openreview.net/pdf?id=B1eBoJStwr) existing work, and partly because they worked well empirically.
